[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer-runs = 10_000_000

[rpc_endpoints]
goerli = "https://goerli.gateway.tenderly.co"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/2emrSzLt95_z1mVvjm4WYtM4LZLYFq9M"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
